export enum UserStageGroup {
  ALL = 'ALL',
  APPLICATION = 'APPLICATION',
  ENTRANCE_TEST = 'ENTRANCE_TEST',
  STUDYING = 'STUDYING',
  PRODUCTION_PRACTICE = 'PRODUCTION_PRACTICE',
  EXAM = 'EXAM'
}
